language: python
python:
  - "2.7"
sudo: required

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libssl-dev
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

branches:
  only:
  - master

before_install:
- eval "${MATRIX_EVAL}"
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version

before_script:
- ulimit -c unlimited -S       # enable core dumps

script:
- source cppKin.sh --install --with_scribe --with_tests

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" ./Tests/bin/sweetPyTests -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
notifications:
  email: false
